import { useEffect, useMemo, useRef, useState } from 'react';
import { AxiosError } from 'axios';
import { Check, Copy, Eye, EyeOff, FileLock2, Link2, LockKeyhole, Pencil, Pin, Plus, Search, Share2, Trash2, Users } from 'lucide-react';
import { notesApi } from '../api/api';
import { AppNote, NoteCategory, NoteFilters, NoteFormData, NotePriority, NoteShare, NoteShareUser, NoteTaskStatus } from '../types';
import { Layout } from '../components/layout/Layout';
import { Button } from '../components/ui/Button';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '../components/ui/Modal';
import { Input } from '../components/ui/Input';
import { SmartLinkChip } from '../components/notes/SmartLinkChip';
import { copyText } from '../lib/clipboard';
import { defaultNoteLinkLabel, getNoteLinkKind } from '../lib/noteLinks';

const categoryLabels: Record<NoteCategory, string> = { GENERAL: 'ทั่วไป', CLIENT_PROJECT: 'ลูกค้า/โปรเจกต์', ACCESS: 'โฮสต์/ข้อมูลเข้าสู่ระบบ', TASK: 'งานที่ต้องทำ' };
const taskLabels: Record<NoteTaskStatus, string> = { TODO: 'ยังไม่ทำ', IN_PROGRESS: 'กำลังทำ', DONE: 'เสร็จแล้ว' };
const priorityLabels: Record<NotePriority, string> = { LOW: 'ต่ำ', MEDIUM: 'ปานกลาง', HIGH: 'สูง' };

type LinkDraft = { url: string; label: string };
type EditorState = {
  category: NoteCategory; title: string; content: string; secureContent: string; encryptContent: boolean; clearSecureContent: boolean;
  tagsText: string; isPinned: boolean; clientName: string; host: string; loginUrl: string; username: string; secret: string; clearSecret: boolean;
  taskStatus: NoteTaskStatus; priority: NotePriority; dueOn: string;
};

const emptyEditor = (): EditorState => ({ category: 'GENERAL', title: '', content: '', secureContent: '', encryptContent: false, clearSecureContent: false, tagsText: '', isPinned: false, clientName: '', host: '', loginUrl: '', username: '', secret: '', clearSecret: false, taskStatus: 'TODO', priority: 'MEDIUM', dueOn: '' });
const noteToEditor = (note: AppNote): EditorState => ({ category: note.category, title: note.title, content: note.content, secureContent: '', encryptContent: note.hasSecureContent, clearSecureContent: false, tagsText: note.tags.join(', '), isPinned: note.isPinned, clientName: note.clientName || '', host: note.host || '', loginUrl: note.loginUrl || '', username: note.username || '', secret: '', clearSecret: false, taskStatus: note.taskStatus || 'TODO', priority: note.priority || 'MEDIUM', dueOn: note.dueOn?.slice(0, 10) || '' });

function errorMessage(error: unknown, fallback: string) { return error instanceof AxiosError ? String(error.response?.data?.error || fallback) : fallback; }
function formatDate(value: string | null) { return value ? new Date(value).toLocaleDateString('th-TH', { day: 'numeric', month: 'short', year: 'numeric' }) : '-'; }
function lineCount(value: string) { return value ? value.split(/\r\n|\r|\n/).length : 0; }
function isOverdue(note: AppNote) { return note.category === 'TASK' && note.taskStatus !== 'DONE' && Boolean(note.dueOn) && new Date(`${note.dueOn!.slice(0, 10)}T00:00:00`) < new Date(new Date().toDateString()); }

function PlainText({ value }: { value: string }) {
  const parts = value.split(/(https?:\/\/[^\s]+)/g);
  return <p className="whitespace-pre-wrap break-words text-sm text-muted-foreground">{parts.map((part, index) => {
    if (!/^https?:\/\//.test(part)) return part;
    const kind = getNoteLinkKind(part);
    return kind && kind !== 'WEBSITE' ? <SmartLinkChip key={index} url={part} label={defaultNoteLinkLabel(part, kind)} kind={kind} className="mx-0.5 align-middle" /> : <a key={index} href={part} target="_blank" rel="noopener noreferrer" className="text-primary underline break-all">{part}</a>;
  })}</p>;
}

export function NotesPage() {
  const [data, setData] = useState<{ notes: AppNote[]; total: number; totalPages: number }>({ notes: [], total: 0, totalPages: 1 });
  const [filters, setFilters] = useState<NoteFilters>({ sort: 'pinned', scope: 'all', page: 1, limit: 24 });
  const [searchInput, setSearchInput] = useState('');
  const [tagInput, setTagInput] = useState('');
  const [loading, setLoading] = useState(true);
  const [editorOpen, setEditorOpen] = useState(false);
  const [viewing, setViewing] = useState<AppNote | null>(null);
  const [editing, setEditing] = useState<AppNote | null>(null);
  const [editor, setEditor] = useState<EditorState>(emptyEditor());
  const [links, setLinks] = useState<LinkDraft[]>([]);
  const [shares, setShares] = useState<NoteShare[]>([]);
  const [shareQuery, setShareQuery] = useState('');
  const [shareResults, setShareResults] = useState<NoteShareUser[]>([]);
  const [saving, setSaving] = useState(false);
  const [passwords, setPasswords] = useState<Record<string, string>>({});
  const [secureContents, setSecureContents] = useState<Record<string, string>>({});
  const [copyStatus, setCopyStatus] = useState('');
  const revealTimers = useRef<Record<string, number>>({});

  const loadNotes = async () => {
    setLoading(true);
    try { setData(await notesApi.getAll(filters)); } catch (error) { alert(errorMessage(error, 'ไม่สามารถโหลด Note ได้')); } finally { setLoading(false); }
  };
  useEffect(() => { loadNotes(); }, [filters]); // eslint-disable-line react-hooks/exhaustive-deps
  useEffect(() => { const timer = window.setTimeout(() => setFilters((previous) => ({ ...previous, q: searchInput || undefined, page: 1 })), 300); return () => window.clearTimeout(timer); }, [searchInput]);
  useEffect(() => { const timer = window.setTimeout(() => setFilters((previous) => ({ ...previous, tag: tagInput.trim() || undefined, page: 1 })), 300); return () => window.clearTimeout(timer); }, [tagInput]);
  useEffect(() => {
    if (shareQuery.trim().length < 2) { setShareResults([]); return; }
    const timer = window.setTimeout(async () => { try { setShareResults(await notesApi.searchUsers(shareQuery.trim())); } catch { setShareResults([]); } }, 250);
    return () => window.clearTimeout(timer);
  }, [shareQuery]);
  useEffect(() => () => Object.values(revealTimers.current).forEach((timer) => window.clearTimeout(timer)), []);
  useEffect(() => {
    const hideAll = () => { setPasswords({}); setSecureContents({}); };
    const onVisibilityChange = () => { if (document.hidden) hideAll(); };
    document.addEventListener('visibilitychange', onVisibilityChange);
    window.addEventListener('blur', hideAll);
    return () => { document.removeEventListener('visibilitychange', onVisibilityChange); window.removeEventListener('blur', hideAll); };
  }, []);

  const tags = useMemo(() => [...new Set(data.notes.flatMap((note) => note.tags))].sort(), [data.notes]);
  const updateFilter = (patch: Partial<NoteFilters>) => setFilters((previous) => ({ ...previous, ...patch, page: 1 }));
  const setField = <K extends keyof EditorState>(key: K, value: EditorState[K]) => setEditor((previous) => ({ ...previous, [key]: value }));
  const hideRevealed = (key: string) => { setPasswords((previous) => { const next = { ...previous }; delete next[key]; return next; }); setSecureContents((previous) => { const next = { ...previous }; delete next[key]; return next; }); if (revealTimers.current[key]) window.clearTimeout(revealTimers.current[key]); delete revealTimers.current[key]; };
  const showTemporarily = (key: string, value: string, setValue: (updater: (previous: Record<string, string>) => Record<string, string>) => void) => {
    setValue((previous) => ({ ...previous, [key]: value }));
    if (revealTimers.current[key]) window.clearTimeout(revealTimers.current[key]);
    revealTimers.current[key] = window.setTimeout(() => hideRevealed(key), 30000);
  };

  const openCreate = () => { setEditing(null); setEditor(emptyEditor()); setLinks([]); setShares([]); setShareQuery(''); setEditorOpen(true); };
  const openEdit = async (note: AppNote) => {
    try { const detail = await notesApi.getOne(note.id); setEditing(detail); setEditor(noteToEditor(detail)); setLinks(detail.links.map((link) => ({ url: link.url, label: link.label }))); setShares(detail.shares || []); setShareQuery(''); setEditorOpen(true); }
    catch (error) { alert(errorMessage(error, 'ไม่สามารถเปิด Note ได้')); }
  };
  const openView = async (note: AppNote) => { try { setViewing(await notesApi.getOne(note.id)); } catch (error) { alert(errorMessage(error, 'ไม่สามารถเปิด Note ได้')); } };
  const addRecipient = (user: NoteShareUser) => { if (shares.some((share) => share.userId === user.id)) return; setShares((previous) => [...previous, { userId: user.id, canViewSecret: false, createdAt: new Date().toISOString(), user }]); setShareQuery(''); setShareResults([]); };

  const buildPayload = (): NoteFormData => {
    const payload: NoteFormData = { category: editor.category, title: editor.title, content: editor.encryptContent ? '' : editor.content, tags: editor.tagsText.split(',').map((tag) => tag.trim()).filter(Boolean), isPinned: editor.isPinned, clientName: editor.clientName || null, links: links.filter((link) => link.url.trim()).map((link) => ({ url: link.url.trim(), label: link.label.trim() || undefined })) };
    if (editor.encryptContent && editor.secureContent) payload.secureContent = editor.secureContent;
    if (editor.clearSecureContent) payload.clearSecureContent = true;
    if (editor.category === 'ACCESS') { payload.host = editor.host || null; payload.loginUrl = editor.loginUrl || null; payload.username = editor.username || null; if (editor.secret) payload.secret = editor.secret; if (editor.clearSecret) payload.clearSecret = true; }
    if (editor.category === 'TASK') { payload.taskStatus = editor.taskStatus; payload.priority = editor.priority; payload.dueOn = editor.dueOn || null; }
    const sensitiveWillExist = editor.category === 'ACCESS' || Boolean(editor.secureContent || (editing?.hasSecureContent && !editor.clearSecureContent));
    payload.shares = shares.map((share) => ({ userId: share.userId, canViewSecret: sensitiveWillExist && share.canViewSecret }));
    return payload;
  };
  const saveNote = async () => {
    if (editor.encryptContent && !editor.secureContent && !editing?.hasSecureContent) { alert('กรอกข้อมูลลับก่อนบันทึก หรือปิดตัวเลือกเข้ารหัสเนื้อหา'); return; }
    setSaving(true);
    try { if (editing) await notesApi.update(editing.id, buildPayload()); else await notesApi.create(buildPayload()); setEditorOpen(false); await loadNotes(); }
    catch (error) { alert(errorMessage(error, 'ไม่สามารถบันทึก Note ได้')); } finally { setSaving(false); }
  };
  const deleteNote = async (note: AppNote) => { if (!window.confirm(`ลบ Note “${note.title}” ?`)) return; try { await notesApi.delete(note.id); await loadNotes(); } catch (error) { alert(errorMessage(error, 'ไม่สามารถลบ Note ได้')); } };
  const quickTaskStatus = async (note: AppNote, taskStatus: NoteTaskStatus) => { try { await notesApi.update(note.id, { taskStatus }); await loadNotes(); } catch (error) { alert(errorMessage(error, 'ไม่สามารถเปลี่ยนสถานะงานได้')); } };
  const revealPassword = async (note: AppNote) => { try { const { secret } = await notesApi.revealSecret(note.id); showTemporarily(`password:${note.id}`, secret, setPasswords); } catch (error) { alert(errorMessage(error, 'ไม่สามารถเปิดดูรหัสผ่านได้')); } };
  const revealSecureContent = async (note: AppNote) => { try { const { content } = await notesApi.revealSecureContent(note.id); showTemporarily(`content:${note.id}`, content, setSecureContents); } catch (error) { alert(errorMessage(error, 'ไม่สามารถเปิดดูข้อมูลลับได้')); } };
  const copyValue = async (value: string, message: string) => { const copied = await copyText(value); setCopyStatus(copied ? message : 'เบราว์เซอร์ไม่อนุญาตให้คัดลอก'); window.setTimeout(() => setCopyStatus(''), 3000); };

  return <Layout>
    <div className="mb-6 flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><h1 className="text-2xl font-bold text-foreground">📝 Note</h1><p className="mt-1 text-sm text-muted-foreground">เก็บข้อมูลลูกค้า งาน เอกสาร และข้อมูลเข้าสู่ระบบอย่างเป็นส่วนตัว</p></div><Button onClick={openCreate} className="gap-2"><Plus size={17} /> เพิ่ม Note</Button></div>
    <section className="mb-6 rounded-xl border border-border bg-card p-4 shadow-sm"><div className="grid grid-cols-1 gap-3 lg:grid-cols-6"><div className="relative lg:col-span-2"><Search size={17} aria-hidden="true" className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground" /><Input aria-label="ค้นหา Note" value={searchInput} onChange={(event) => setSearchInput(event.target.value)} className="pl-9" placeholder="ค้นหาชื่อ เนื้อหา ลูกค้า เอกสาร..." /></div><select aria-label="กรองตามประเภท" value={filters.category || ''} onChange={(event) => updateFilter({ category: event.target.value as NoteCategory || undefined })} className="h-10 rounded-lg border border-input bg-background px-3 text-sm"><option value="">ทุกประเภท</option>{Object.entries(categoryLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><select aria-label="กรองตามสถานะงาน" value={filters.taskStatus || ''} onChange={(event) => updateFilter({ taskStatus: event.target.value as NoteTaskStatus || undefined })} className="h-10 rounded-lg border border-input bg-background px-3 text-sm"><option value="">ทุกสถานะงาน</option>{Object.entries(taskLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><select aria-label="กรองตามเจ้าของ" value={filters.scope || 'all'} onChange={(event) => updateFilter({ scope: event.target.value as 'all' | 'owned' | 'shared' })} className="h-10 rounded-lg border border-input bg-background px-3 text-sm"><option value="all">ทั้งหมด</option><option value="owned">ของฉัน</option><option value="shared">แชร์กับฉัน</option></select><select aria-label="เรียง Note" value={filters.sort || 'pinned'} onChange={(event) => updateFilter({ sort: event.target.value as NoteFilters['sort'] })} className="h-10 rounded-lg border border-input bg-background px-3 text-sm"><option value="pinned">ปักหมุดก่อน</option><option value="updated">แก้ไขล่าสุด</option><option value="due">กำหนดส่ง</option><option value="title">ชื่อ A-Z</option></select></div><div className="mt-3 flex flex-wrap items-center gap-3"><Input aria-label="กรองตามแท็ก" value={tagInput} onChange={(event) => setTagInput(event.target.value)} placeholder="กรองแท็ก เช่น ลูกค้าสำคัญ" className="max-w-xs" list="note-tags" /><datalist id="note-tags">{tags.map((tag) => <option key={tag} value={tag} />)}</datalist><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={Boolean(filters.overdue)} onChange={(event) => updateFilter({ overdue: event.target.checked || undefined })} /> งานเกินกำหนด</label><span className="text-sm text-muted-foreground">พบ {data.total} Note</span></div></section>
    {loading ? <div className="py-16 text-center text-muted-foreground">กำลังโหลด Note...</div> : data.notes.length === 0 ? <div className="rounded-xl border border-dashed border-border bg-card py-16 text-center"><div className="text-4xl">📝</div><h2 className="mt-3 font-semibold">ยังไม่พบ Note</h2><p className="mt-1 text-sm text-muted-foreground">เพิ่ม Note แรกเพื่อเก็บข้อมูลที่ค้นหาได้ง่าย</p></div> : <div className="grid items-start grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-3">{data.notes.map((note) => <NoteCard key={note.id} note={note} onView={() => openView(note)} onEdit={() => openEdit(note)} onDelete={() => deleteNote(note)} onTaskStatus={(status) => quickTaskStatus(note, status)} />)}</div>}
    {data.totalPages > 1 && <div className="mt-6 flex justify-center gap-3"><Button variant="outline" size="sm" disabled={(filters.page || 1) <= 1} onClick={() => setFilters((previous) => ({ ...previous, page: (previous.page || 1) - 1 }))}>ก่อนหน้า</Button><span className="self-center text-sm">หน้า {filters.page || 1} / {data.totalPages}</span><Button variant="outline" size="sm" disabled={(filters.page || 1) >= data.totalPages} onClick={() => setFilters((previous) => ({ ...previous, page: (previous.page || 1) + 1 }))}>ถัดไป</Button></div>}
    <EditorDialog open={editorOpen} onOpenChange={setEditorOpen} editing={editing} editor={editor} setEditor={setEditor} setField={setField} links={links} setLinks={setLinks} shares={shares} setShares={setShares} shareQuery={shareQuery} setShareQuery={setShareQuery} shareResults={shareResults} addRecipient={addRecipient} saving={saving} onSave={saveNote} />
    <ViewerDialog note={viewing} password={viewing ? passwords[`password:${viewing.id}`] : undefined} secureContent={viewing ? secureContents[`content:${viewing.id}`] : undefined} onOpenChange={(open) => !open && setViewing(null)} onEdit={() => { if (viewing) { setViewing(null); openEdit(viewing); } }} onRevealPassword={() => viewing && revealPassword(viewing)} onRevealContent={() => viewing && revealSecureContent(viewing)} onHidePassword={() => viewing && hideRevealed(`password:${viewing.id}`)} onHideContent={() => viewing && hideRevealed(`content:${viewing.id}`)} onCopy={(value, message) => copyValue(value, message)} />
    <div role="status" aria-live="polite" className="sr-only">{copyStatus}</div>
  </Layout>;
}

function NoteCard({ note, onView, onEdit, onDelete, onTaskStatus }: { note: AppNote; onView: () => void; onEdit: () => void; onDelete: () => void; onTaskStatus: (status: NoteTaskStatus) => void }) {
  const overdue = isOverdue(note);
  const extraLinks = Math.max(0, note.links.length - 2);
  return <article className={`self-start rounded-xl border bg-card p-4 shadow-sm ${overdue ? 'border-red-300 dark:border-red-800' : 'border-border'}`}>
    <div className="flex items-start justify-between gap-3"><div className="min-w-0"><div className="mb-2 flex flex-wrap items-center gap-2"><span className="rounded-full bg-blue-50 px-2 py-0.5 text-xs text-blue-700 dark:bg-blue-950/60 dark:text-blue-200">{categoryLabels[note.category]}</span>{note.isShared && <span className="rounded-full bg-violet-50 px-2 py-0.5 text-xs text-violet-700 dark:bg-violet-950/60 dark:text-violet-200">แชร์กับฉัน</span>}{note.isPinned && <Pin size={14} aria-label="ปักหมุดแล้ว" className="text-amber-500 fill-amber-500" />}</div><button type="button" onClick={onView} className="text-left font-semibold text-foreground hover:text-primary focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring">{note.title}</button></div>{note.canEdit && <Button variant="ghost" size="sm" onClick={onEdit} aria-label={`แก้ไข Note ${note.title}`}><Pencil size={16} /></Button>}</div>
    {note.clientName && <p className="mt-2 text-sm text-muted-foreground">👤 {note.clientName}</p>}
    {note.hasSecureContent ? <div className="mt-3 rounded-lg border border-amber-200 bg-amber-50/60 p-3 text-sm dark:border-amber-800 dark:bg-amber-950/30"><div className="flex items-center gap-2 font-medium text-amber-800 dark:text-amber-200"><FileLock2 size={16} /> ข้อมูลลับ · {note.secureContentLineCount} บรรทัด</div><p className="mt-1 text-xs text-muted-foreground">กดดูรายละเอียดเพื่อเปิดดูตามสิทธิ์</p></div> : note.content && <div className="mt-3 line-clamp-4"><PlainText value={note.content} /></div>}
    {note.category === 'ACCESS' && <div className="mt-3 rounded-lg bg-muted/60 p-3 text-sm"><div className="font-medium">🔐 {note.host || 'ข้อมูลเข้าสู่ระบบ'}</div>{note.username && <div className="mt-1 text-muted-foreground">Username: {note.username}</div>}{note.hasSecret && <div className="mt-2 text-xs text-muted-foreground">•••••••• ข้อมูลลับ</div>}</div>}
    {note.links.length > 0 && <div className="mt-3 flex flex-wrap gap-2">{note.links.slice(0, 2).map((link) => <SmartLinkChip key={link.id} {...link} />)}{extraLinks > 0 && <button type="button" onClick={onView} className="rounded-lg border border-border bg-muted px-2.5 py-1.5 text-xs font-medium hover:bg-accent">+ อีก {extraLinks} ลิงก์</button>}</div>}
    {note.category === 'TASK' && <div className={`mt-3 rounded-lg p-3 text-sm ${overdue ? 'bg-red-50 text-red-700 dark:bg-red-950/40 dark:text-red-200' : 'bg-muted/60'}`}><div className="flex justify-between gap-2"><span>{note.priority && `ความสำคัญ: ${priorityLabels[note.priority]}`}</span>{note.dueOn && <span>{overdue ? 'เกินกำหนด: ' : 'กำหนด: '}{formatDate(note.dueOn)}</span>}</div>{note.canEdit && <select aria-label={`เปลี่ยนสถานะงาน ${note.title}`} value={note.taskStatus || 'TODO'} onChange={(event) => onTaskStatus(event.target.value as NoteTaskStatus)} className="mt-2 rounded border border-input bg-background px-2 py-1 text-sm"><option value="TODO">ยังไม่ทำ</option><option value="IN_PROGRESS">กำลังทำ</option><option value="DONE">เสร็จแล้ว</option></select>}</div>}
    {note.tags.length > 0 && <div className="mt-3 flex flex-wrap gap-1.5">{note.tags.map((tag) => <span key={tag} className="rounded bg-secondary/10 px-2 py-0.5 text-xs text-secondary-foreground">#{tag}</span>)}</div>}
    <div className="mt-4 flex items-center justify-between border-t border-border pt-3"><span className="text-xs text-muted-foreground">แก้ไข {formatDate(note.updatedAt)}</span><div className="flex gap-1"><Button variant="outline" size="sm" onClick={onView} className="h-8 px-2 text-xs">ดูทั้งหมด</Button>{note.canEdit && <Button variant="ghost" size="sm" onClick={onDelete} aria-label={`ลบ Note ${note.title}`} className="h-8 px-2 text-red-500 hover:text-red-700"><Trash2 size={15} /></Button>}</div></div>
  </article>;
}

function EditorDialog(props: { open: boolean; onOpenChange: (open: boolean) => void; editing: AppNote | null; editor: EditorState; setEditor: React.Dispatch<React.SetStateAction<EditorState>>; setField: <K extends keyof EditorState>(key: K, value: EditorState[K]) => void; links: LinkDraft[]; setLinks: React.Dispatch<React.SetStateAction<LinkDraft[]>>; shares: NoteShare[]; setShares: (shares: NoteShare[]) => void; shareQuery: string; setShareQuery: (value: string) => void; shareResults: NoteShareUser[]; addRecipient: (user: NoteShareUser) => void; saving: boolean; onSave: () => void }) {
  const { open, onOpenChange, editing, editor, setEditor, setField, links, setLinks, shares, setShares, shareQuery, setShareQuery, shareResults, addRecipient, saving, onSave } = props;
  const hasExistingSecret = Boolean(editing?.hasSecret);
  const hasExistingSecureContent = Boolean(editing?.hasSecureContent);
  const sensitiveWillExist = editor.category === 'ACCESS' || Boolean(editor.secureContent || (hasExistingSecureContent && !editor.clearSecureContent));
  const toggleEncryption = (checked: boolean) => setEditor((previous) => {
    if (!checked && hasExistingSecureContent) return previous;
    return checked ? { ...previous, encryptContent: true, secureContent: previous.secureContent || previous.content, content: '' } : { ...previous, encryptContent: false, content: previous.secureContent, secureContent: '' };
  });
  const replaceSecureContent = (value: string) => setEditor((previous) => ({ ...previous, secureContent: value, clearSecureContent: false }));
  const toggleClearSecureContent = (checked: boolean) => setEditor((previous) => ({ ...previous, clearSecureContent: checked, secureContent: checked ? '' : previous.secureContent }));
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-h-[90vh] max-w-3xl overflow-y-auto"><DialogHeader><DialogTitle>{editing ? 'แก้ไข Note' : 'เพิ่ม Note'}</DialogTitle><DialogDescription>เก็บข้อความ เอกสาร และข้อมูลลับใน Note เดียว โดยผู้รับแชร์อ่านได้อย่างเดียว</DialogDescription></DialogHeader><div className="space-y-4 pr-1">
    <div className="grid grid-cols-1 gap-4 sm:grid-cols-2"><Input label="ชื่อ Note" value={editor.title} onChange={(event) => setField('title', event.target.value)} maxLength={200} required /><label className="space-y-2 text-sm font-medium">ประเภท<select value={editor.category} onChange={(event) => setField('category', event.target.value as NoteCategory)} className="h-10 w-full rounded-md border border-input bg-background px-3 font-normal">{Object.entries(categoryLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label></div>
    <Input label="ชื่อลูกค้า/โปรเจกต์ (ไม่บังคับ)" value={editor.clientName} onChange={(event) => setField('clientName', event.target.value)} maxLength={200} />
    <section className={`rounded-xl border p-4 ${editor.encryptContent ? 'border-amber-200 bg-amber-50/40 dark:border-amber-800 dark:bg-amber-950/25' : 'border-border bg-muted/30'}`}><label className="flex items-center gap-2 text-sm font-medium"><input type="checkbox" checked={editor.encryptContent} disabled={hasExistingSecureContent} onChange={(event) => toggleEncryption(event.target.checked)} /><FileLock2 size={16} /> เนื้อหานี้มีข้อมูลลับ</label>{editor.encryptContent ? <><label className="mt-3 block space-y-2 text-sm font-medium">{hasExistingSecureContent ? 'แทนที่ข้อมูลลับเดิม (เว้นว่างเพื่อคงเดิม)' : 'ข้อมูลลับ (เข้ารหัสก่อนบันทึก)'}<textarea value={editor.secureContent} disabled={editor.clearSecureContent} onChange={(event) => replaceSecureContent(event.target.value)} maxLength={50000} rows={7} className="w-full rounded-md border border-input bg-background px-3 py-2 font-normal disabled:cursor-not-allowed disabled:opacity-60" placeholder={editor.clearSecureContent ? 'เลือกไว้เพื่อลบข้อมูลลับเดิม' : 'วางรายการ Gmail หรือข้อมูลลับหลายบรรทัด'} /></label>{hasExistingSecureContent && <label className="mt-2 flex items-center gap-2 text-sm text-red-700 dark:text-red-300"><input type="checkbox" checked={editor.clearSecureContent} onChange={(event) => toggleClearSecureContent(event.target.checked)} /> ลบข้อมูลลับที่บันทึกไว้</label>}<p className="mt-2 text-xs text-muted-foreground">เนื้อหาที่เข้ารหัสค้นหาจากข้อความภายในไม่ได้ และจะแสดงได้เฉพาะผู้มีสิทธิ์</p></> : <label className="mt-3 block space-y-2 text-sm font-medium">เนื้อหา (plain text)<textarea value={editor.content} onChange={(event) => setField('content', event.target.value)} maxLength={50000} rows={7} className="w-full rounded-md border border-input bg-background px-3 py-2 font-normal" placeholder="เก็บรายละเอียดหรือรายการอีเมลหลายบรรทัด" /></label>}</section>
    <Input label="แท็ก (คั่นด้วย , ได้สูงสุด 20 แท็ก)" value={editor.tagsText} onChange={(event) => setField('tagsText', event.target.value)} />
    <label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={editor.isPinned} onChange={(event) => setField('isPinned', event.target.checked)} /> <Pin size={15} /> ปักหมุดไว้ด้านบน</label>
    <section className="rounded-xl border border-border bg-muted/30 p-4"><div className="mb-3 flex items-center gap-2 font-medium"><Link2 size={16} /> เอกสารและลิงก์ <span className="text-xs font-normal text-muted-foreground">Google Sheets/Docs จะแสดงเป็น Smart Link</span></div><div className="space-y-2">{links.map((link, index) => <div key={index} className="grid grid-cols-1 gap-2 sm:grid-cols-[1fr_0.7fr_auto]"><Input aria-label={`URL เอกสาร ${index + 1}`} value={link.url} onChange={(event) => setLinks((previous) => previous.map((item, itemIndex) => itemIndex === index ? { ...item, url: event.target.value } : item))} placeholder="https://..." /><Input aria-label={`ชื่อเอกสาร ${index + 1}`} value={link.label} onChange={(event) => setLinks((previous) => previous.map((item, itemIndex) => itemIndex === index ? { ...item, label: event.target.value } : item))} placeholder="ชื่อที่แสดง" /><Button type="button" variant="ghost" size="sm" aria-label={`ลบลิงก์ ${index + 1}`} className="text-red-600" onClick={() => setLinks((previous) => previous.filter((_, itemIndex) => itemIndex !== index))}>ลบ</Button></div>)}</div>{links.length < 20 && <Button type="button" variant="outline" size="sm" className="mt-3" onClick={() => setLinks((previous) => [...previous, { url: '', label: '' }])}><Plus size={14} className="mr-1" /> เพิ่มลิงก์</Button>}</section>
    {editor.category === 'ACCESS' && <section className="space-y-3 rounded-xl border border-amber-200 bg-amber-50/40 p-4 dark:border-amber-800 dark:bg-amber-950/25"><div className="flex items-center gap-2 font-medium"><LockKeyhole size={16} /> ข้อมูลเข้าสู่ระบบ</div><div className="grid grid-cols-1 gap-3 sm:grid-cols-2"><Input label="Host/บริการ" value={editor.host} onChange={(event) => setField('host', event.target.value)} /><Input label="URL" type="url" value={editor.loginUrl} onChange={(event) => setField('loginUrl', event.target.value)} placeholder="https://..." /><Input label="Username" value={editor.username} onChange={(event) => setField('username', event.target.value)} /><Input label={hasExistingSecret ? 'ตั้งรหัสผ่านใหม่ (เว้นว่างเพื่อคงเดิม)' : 'Password'} type="password" value={editor.secret} onChange={(event) => setField('secret', event.target.value)} autoComplete="new-password" /></div>{hasExistingSecret && <label className="flex items-center gap-2 text-sm text-red-700 dark:text-red-300"><input type="checkbox" checked={editor.clearSecret} onChange={(event) => setField('clearSecret', event.target.checked)} /> ลบรหัสผ่านที่บันทึกไว้</label>}</section>}
    {editor.category === 'TASK' && <section className="grid grid-cols-1 gap-3 rounded-xl border border-blue-200 bg-blue-50/40 p-4 dark:border-blue-800 dark:bg-blue-950/25 sm:grid-cols-3"><label className="space-y-1 text-sm">สถานะ<select value={editor.taskStatus} onChange={(event) => setField('taskStatus', event.target.value as NoteTaskStatus)} className="h-10 w-full rounded border border-input bg-background px-2">{Object.entries(taskLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label className="space-y-1 text-sm">ความสำคัญ<select value={editor.priority} onChange={(event) => setField('priority', event.target.value as NotePriority)} className="h-10 w-full rounded border border-input bg-background px-2">{Object.entries(priorityLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><Input label="กำหนดส่ง" type="date" value={editor.dueOn} onChange={(event) => setField('dueOn', event.target.value)} /></section>}
    <section className="rounded-xl border border-violet-200 bg-violet-50/40 p-4 dark:border-violet-800 dark:bg-violet-950/25"><div className="mb-2 flex items-center gap-2 font-medium"><Users size={16} /> แชร์ Note <span className="text-xs font-normal text-muted-foreground">ผู้รับอ่านได้อย่างเดียว</span></div><Input aria-label="ค้นหาผู้รับแชร์" value={shareQuery} onChange={(event) => setShareQuery(event.target.value)} placeholder="ค้นหาชื่อหรืออีเมลผู้ใช้ (อย่างน้อย 2 ตัวอักษร)" />{shareResults.length > 0 && <div className="mt-2 rounded border bg-background">{shareResults.map((user) => <button key={user.id} onClick={() => addRecipient(user)} type="button" className="block w-full px-3 py-2 text-left text-sm hover:bg-muted">{user.name} <span className="text-muted-foreground">({user.email})</span></button>)}</div>}<div className="mt-3 space-y-2">{shares.map((share) => <div key={share.userId} className="flex flex-wrap items-center justify-between gap-2 rounded bg-background px-3 py-2 text-sm"><span>{share.user.name} <span className="text-muted-foreground">{share.user.email}</span></span><div className="flex items-center gap-2"><label className="flex items-center gap-1 text-xs"><input type="checkbox" disabled={!sensitiveWillExist} checked={share.canViewSecret} onChange={(event) => setShares(shares.map((item) => item.userId === share.userId ? { ...item, canViewSecret: event.target.checked } : item))} /> อนุญาตดูข้อมูลลับ</label><Button type="button" variant="ghost" size="sm" aria-label={`ลบผู้รับแชร์ ${share.user.name}`} className="h-7 px-2 text-red-600" onClick={() => setShares(shares.filter((item) => item.userId !== share.userId))}>ลบ</Button></div></div>)}</div></section>
    <div className="flex gap-3 pt-2"><Button type="button" variant="outline" className="flex-1" onClick={() => onOpenChange(false)}>ยกเลิก</Button><Button type="button" className="flex-1" disabled={saving || !editor.title.trim()} onClick={onSave}>{saving ? 'กำลังบันทึก...' : <><Check size={16} className="mr-1" /> บันทึก Note</>}</Button></div>
  </div></DialogContent></Dialog>;
}

function ViewerDialog({ note, password, secureContent, onOpenChange, onEdit, onRevealPassword, onRevealContent, onHidePassword, onHideContent, onCopy }: { note: AppNote | null; password?: string; secureContent?: string; onOpenChange: (open: boolean) => void; onEdit: () => void; onRevealPassword: () => void; onRevealContent: () => void; onHidePassword: () => void; onHideContent: () => void; onCopy: (value: string, message: string) => void }) {
  if (!note) return null;
  return <Dialog open onOpenChange={onOpenChange}><DialogContent className="max-h-[85vh] max-w-2xl overflow-y-auto"><DialogHeader><DialogTitle>{note.title}</DialogTitle><DialogDescription>รายละเอียด Note และเอกสารที่เกี่ยวข้อง</DialogDescription></DialogHeader><div className="space-y-4"><div className="flex flex-wrap gap-2"><span className="rounded-full bg-blue-50 px-2 py-1 text-xs text-blue-700 dark:bg-blue-950/60 dark:text-blue-200">{categoryLabels[note.category]}</span>{note.isShared && <span className="rounded-full bg-violet-50 px-2 py-1 text-xs text-violet-700 dark:bg-violet-950/60 dark:text-violet-200"><Share2 size={12} className="mr-1 inline" /> โดย {note.owner.name}</span>}</div>{note.clientName && <div className="text-sm">👤 {note.clientName}</div>}{note.hasSecureContent ? <SecureContentControl note={note} content={secureContent} onReveal={onRevealContent} onHide={onHideContent} onCopy={onCopy} /> : <section><div className="mb-2 flex items-center justify-between gap-2"><h3 className="font-medium">เนื้อหา {note.content && <span className="text-xs font-normal text-muted-foreground">· {lineCount(note.content)} บรรทัด</span>}</h3>{note.content && <Button variant="outline" size="sm" onClick={() => onCopy(note.content, 'คัดลอกเนื้อหาทั้งหมดแล้ว')}><Copy size={14} className="mr-1" />คัดลอกทั้งหมด</Button>}</div><PlainText value={note.content || 'ไม่มีเนื้อหา'} /></section>}{note.links.length > 0 && <section className="border-t border-border pt-4"><h3 className="mb-2 font-medium">เอกสารที่เกี่ยวข้อง</h3><div className="flex flex-wrap gap-2">{note.links.map((link) => <SmartLinkChip key={link.id} {...link} />)}</div><Button variant="outline" size="sm" className="mt-3" onClick={() => onCopy(note.links.map((link) => link.url).join('\n'), 'คัดลอกลิงก์ทั้งหมดแล้ว')}><Copy size={14} className="mr-1" />คัดลอกลิงก์ทั้งหมด</Button></section>}{note.category === 'ACCESS' && <section className="rounded-lg bg-muted p-3 text-sm space-y-2"><div>Host/บริการ: {note.host || '-'}</div>{note.loginUrl && <SmartLinkChip url={note.loginUrl} label="เปิดหน้าเข้าสู่ระบบ" kind="WEBSITE" />}<div>Username: {note.username || '-'}</div>{note.hasSecret && <PasswordControl note={note} password={password} onReveal={onRevealPassword} onHide={onHidePassword} onCopy={onCopy} />}</section>}{note.category === 'TASK' && <div className="rounded-lg bg-muted p-3 text-sm">{taskLabels[note.taskStatus || 'TODO']} · {note.priority && priorityLabels[note.priority]} · กำหนด {formatDate(note.dueOn)}</div>}{note.tags.length > 0 && <div className="flex flex-wrap gap-1">{note.tags.map((tag) => <span key={tag} className="rounded bg-secondary/10 px-2 py-1 text-xs">#{tag}</span>)}</div>}<div className="flex gap-3 border-t border-border pt-4"><Button variant="outline" className="flex-1" onClick={() => onOpenChange(false)}>ปิด</Button>{note.canEdit && <Button className="flex-1" onClick={onEdit}><Pencil size={16} className="mr-1" />แก้ไข</Button>}</div></div></DialogContent></Dialog>;
}

function PasswordControl({ note, password, onReveal, onHide, onCopy }: { note: AppNote; password?: string; onReveal: () => void; onHide: () => void; onCopy: (value: string, message: string) => void }) {
  if (!note.canViewSecret) return <div className="text-xs text-muted-foreground">•••••••• ไม่มีสิทธิ์ดูข้อมูลลับ</div>;
  return <div className="flex items-center gap-2"><code className="min-w-0 flex-1 truncate rounded bg-background px-2 py-1">{password || '••••••••'}</code>{password ? <><Button variant="ghost" size="sm" className="h-8 px-2" onClick={() => onCopy(password, 'คัดลอกรหัสผ่านแล้ว')} aria-label="คัดลอกรหัสผ่าน"><Copy size={14} /></Button><Button variant="ghost" size="sm" className="h-8 px-2" onClick={onHide} aria-label="ซ่อนรหัสผ่าน"><EyeOff size={14} /></Button></> : <Button variant="soft-primary" size="sm" onClick={onReveal}><Eye size={14} className="mr-1" />ดูรหัส</Button>}</div>;
}

function SecureContentControl({ note, content, onReveal, onHide, onCopy }: { note: AppNote; content?: string; onReveal: () => void; onHide: () => void; onCopy: (value: string, message: string) => void }) {
  if (!note.canViewSecureContent) return <section className="rounded-lg border border-amber-200 bg-amber-50/60 p-4 dark:border-amber-800 dark:bg-amber-950/30"><div className="flex items-center gap-2 font-medium"><FileLock2 size={17} /> ข้อมูลลับ · {note.secureContentLineCount} บรรทัด</div><p className="mt-1 text-sm text-muted-foreground">คุณไม่มีสิทธิ์ดูข้อมูลนี้</p></section>;
  return <section className="rounded-lg border border-amber-200 bg-amber-50/60 p-4 dark:border-amber-800 dark:bg-amber-950/30"><div className="flex items-center justify-between gap-2"><div className="flex items-center gap-2 font-medium"><FileLock2 size={17} /> ข้อมูลลับ · {note.secureContentLineCount} บรรทัด</div>{content ? <div className="flex gap-1"><Button variant="ghost" size="sm" onClick={() => onCopy(content, 'คัดลอกข้อมูลลับแล้ว')} aria-label="คัดลอกข้อมูลลับ"><Copy size={14} /></Button><Button variant="ghost" size="sm" onClick={onHide} aria-label="ซ่อนข้อมูลลับ"><EyeOff size={14} /></Button></div> : <Button variant="soft-warning" size="sm" onClick={onReveal}><Eye size={14} className="mr-1" />เปิดดู</Button>}</div>{content ? <div className="mt-3 rounded bg-background p-3"><PlainText value={content} /></div> : <p className="mt-1 text-sm text-muted-foreground">ซ่อนอัตโนมัติภายใน 30 วินาทีหลังเปิดดู</p>}</section>;
}
